stages:
  - preparation
  - testing
  - build
# variables:
#   MYSQL_ROOT_PASSWORD: root
#   MYSQL_USER: mysql_user
#   MYSQL_PASSWORD: mysql_password
#   MYSQL_DATABASE: mysql_db
#   DB_HOST: mysql
# https://github.com/ohdearapp/gitlab-ci-pipeline-for-laravel/blob/master/.gitlab-ci.yml
image: composer:2.0.11

composer:
  stage: preparation
  script:
    - php -v
    - composer install --prefer-dist --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - ./*
    expire_in: 1 days
    when: always

phpunit:
  stage: testing
  script:
    - php -v
    - php ./vendor/phpunit/phpunit/phpunit --version
    - php ./vendor/phpunit/phpunit/phpunit
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

behat:
  stage: testing
  script:
    - php ./vendor/bin/behat --version
    - php ./vendor/bin/behat
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

build:development-docker-image:
  stage: build
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u gitlab+deploy-token-2 -p ayXzgFLwy_jAQvYX9-w7 gitlab.groep-7.xyz:5050
    - docker build -t gitlab.groep-7.xyz:5050/joep/ipsenh-backend:development .
    - docker push gitlab.groep-7.xyz:5050/joep/ipsenh-backend:development
  only:
    - development

build:production-docker-image:
  stage: build
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u gitlab+deploy-token-2 -p ayXzgFLwy_jAQvYX9-w7 gitlab.groep-7.xyz:5050
    - docker build -t gitlab.groep-7.xyz:5050/joep/ipsenh-backend:master .
    - docker push gitlab.groep-7.xyz:5050/joep/ipsenh-backend:master
  only:
    - master
