stages:
 - build

build:
  stage: build
  image: composer:2.0.11
  only:
    - master
    - develop
  script:
    - composer install
    - 
  # artifacts:
  #   paths:
  #     - dist/
  #   expire_in: 2 hours
  # cache:
  #   paths:
  #     - node_modules/