stages:
 - build

build:
  stage: build
  image: composer:2.0.11
  only:
    - master
  script:
    - npm install -g @angular/cli@9.1.0
    - npm install
    - ng build 
  artifacts:
    paths:
      - dist/
    expire_in: 2 hours
  cache:
    paths:
      - node_modules/