stages:
  - preparation
  - testing
  - build
  - deploy
# variables:
#   MYSQL_ROOT_PASSWORD: root
#   MYSQL_USER: mysql_user
#   MYSQL_PASSWORD: mysql_password
#   MYSQL_DATABASE: mysql_db
#   DB_HOST: mysql
# https://github.com/ohdearapp/gitlab-ci-pipeline-for-laravel/blob/master/.gitlab-ci.yml
image: composer:2.0.11

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  script:
    - php -v
    - composer install --prefer-dist --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

phpunit:
  stage: testing
  # services:
  #   - name: mysql:8.0
  #     command: ["--default-authentication-plugin=mysql_native_password"]
  # Download the artifacts for these jobs
  dependencies:
    - composer
  script:
    - php -v
    - php ./vendor/phpunit/phpunit/phpunit --version
    - php ./vendor/phpunit/phpunit/phpunit
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

behat:
  stage: testing
  # services:
  #   - name: mysql:8.0
  #     command: ["--default-authentication-plugin=mysql_native_password"]
  # Download the artifacts for these jobs
  dependencies:
    - composer
  script:
    - php ./vendor/bin/behat --version
    - php ./vendor/bin/behat
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

build:development-docker-image:
  stage: build
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u $PROJECT_TOKEN_USERNAME -p $PROJECT_TOKEN_PASSWORD $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_REGISTRY/joep/ipsenh-backend:development .
    - docker push $CONTAINER_REGISTRY/joep/ipsenh-backend:development

build:production-docker-image:
  stage: build
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u $PROJECT_TOKEN_USERNAME -p $PROJECT_TOKEN_PASSWORD $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_REGISTRY/joep/ipsenh-backend .
    - docker push $CONTAINER_REGISTRY/joep/ipsenh-backend
  only:
    - master

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh -o StrictHostKeyChecking=no deployer@groep-7.xyz "cd ~; ls -l"
