version: "3.9"

services:
  backend:
    build: .
    container_name: lumen
    environment:
      APP_ENV: '${APP_ENV}'
      APP_DEBUG: '${APP_DEBUG}'
      APP_URL: '${APP_URL}'
    volumes:
      - '.:/var/www/html/'
      - vendor:/var/www/html/vendor
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  vendor:
